# All Computational Models are Wrong

Zoey Liu

(Thank you to Jordan Kodner)

## The Tolerance Principle at a high level and a very high level

 Virtually all potential rules of a language are bound to have (arbitrary) exceptions, so the learner shouldn't hold rules to a standard of perfection. For example, a clear rule of English, suffix *-ed* to the verb to make past tense has plenty of exceptions. The real question is how many exceptions, as a proportion of the total number of types that are expected to follow the rule, can be tolerated. If there are “too many” exceptions, the rule is probably not a good one for the learner to acquire. If there aren’t “too many,” the learner should acquire the rule. The Tolerance Principle provides this threshold: If the rule should apply to $N$ types that the child knows so far, but the child has learned $e$ exceptions to the rule, the child should learn the rule + memorize the exceptions if $e$ < $\theta$, the tolerance threshold. If $e$ > $\theta$, it’s back to the drawing board. Either just memorize it all as exceptions, or try again with a different rule.

One one hand, language is incredibly arbitrary. On the other, it is ex-traordinarily rule-governed. This duality is what has secured linguistics its privileged role in the cognitive sciences. That said, it also presents an enormous challenge to language learners, who each have to work out for themselves what is productive/rule-governed and what is non- productive/arbitrary. The Tolerance Principle is a precise metric which the learner can use to make this decision.

**TP**: $\theta = \frac{N}{lnN}$

**The question**: Is $e < \theta$ ?

math.log

In [1]:
import math

## Exercise 1: Performing some Calculations

1.   Say the learner hypothesizes some rule for which $N = 40$ and $e = 10$. Is the rule productive? Show your work by calculating $\theta$. 

> 10

In [2]:
# Insert your code here
def calc_theta(N: int, e: int):
    theta = N / math.log(N)
    if isinstance(e, int):
        if e <= theta:
            print(f"{e} <= {theta}, so there aren't 'too many,' the learner should acquire the rule.")  
        else:
            print(f"{e} > {theta}, so there are 'too many' exceptions, the rule is probably not a good one for the learner to acquire.")
    return theta

In [3]:
calc_theta(N=40, e=10)

10 <= 10.843401227272672, so there aren't 'too many,' the learner should acquire the rule.

10.843401227272672

2. Do the same for $N = 940$ and $e = 280$.

> 137

In [4]:
# Insert your code here
calc_theta(N=940, e=280)

280 > 137.3088656428906, so there are 'too many' exceptions, the rule is probably not a good one for the learner to acquire.

137.3088656428906

3. If $N = 320$ for some rule, what is the maximum number of exceptions it can tolerate?

> Max e = 55

In [5]:
# Insert your code here
def calc_e(N: int):
    theta = N / math.log(N)
    print(f"Max e = {theta} because e <= {theta}")

In [6]:
calc_e(N=320)

Max e = 55.47541481019213 because e <= 55.47541481019213

4. If there are $e = 34$ exceptions to a rule, at least how large must $N$ be for them to be tolerable?

> 175.76 when we round 2 decimal places.

In [51]:
# Insert your code here
Ns = [20, 175.76, 180, 200, 2000]
theta_for_n = {}

for n in Ns:
    theta_at_n_i = calc_theta(n, e=34)
    theta_for_n[n] = round(theta_at_n_i, 2)
theta_for_n

34 > 6.676164013906681, so there are 'too many' exceptions, the rule is probably not a good one for the learner to acquire.
34 <= 34.001922850795424, so there aren't 'too many,' the learner should acquire the rule.
34 <= 34.66233307313987, so there aren't 'too many,' the learner should acquire the rule.
34 <= 37.74783316355097, so there aren't 'too many,' the learner should acquire the rule.
34 <= 263.12664984790376, so there aren't 'too many,' the learner should acquire the rule.

{20: 6.68, 175.76: 34.0, 180: 34.66, 200: 37.75, 2000: 263.13}

## Exercise 2 Falling out of Productivity

1. It is relatively easy for a rule to fall out of productivity because $\theta$ is larger relative to small $N$ than large $N$. Let’s test this out. What are the $\theta$ for $N = 20$, $N = 200$, and $N = 2000$?

In [8]:
# Insert your code here
Ns = [20, 200, 2000]
theta_for_n = {}

for n in Ns:
    theta_at_n_i = calc_theta(n, e=None)
    theta_for_n[n] = theta_at_n_i
theta_for_n

{20: 6.676164013906681, 200: 37.74783316355097, 2000: 263.12664984790376}

2. Using the numbers calculated in the previous question, calculate the ratio of $\theta$ to $N$ for each $N$. Does the ratio rise or fall as $N$ increases?

In [9]:
# Insert your code here
theta_to_n_ratios = []
for key, value in theta_for_n.items():
    theta_to_n_ratio = key // value
    theta_to_n_ratios.append(theta_to_n_ratio)
    
theta_to_n_ratios

[2.0, 5.0, 7.0]

## Exercise 3 Working with Real Data

In this section, we will be working with some child production data. We will be working with some English past tense forms produced by Sarah from the Brown Corpus in the [CHILDES](https://childes.talkbank.org/) database. The data is stored in sarah_brown.txt

### Strong, Weak, Semi-Weak, and Suppletive

Four kinds of verbs are traditionally distinguished in traditional Germanic linguistics, strong verbs, weak verbs, semi-weak verbs, and suppletive verbs. 

1. stem: [[Lexicon of linguistics](https://lexicon.hum.uu.nl/) by Johan Kerstens, Eddy Ruys, Joost Zwarts]
    - MORPHOLOGY: a term which is commonly used for the **uninflected** part of a word. 
        - inflected [dynamically changes to encode grammatical information such as tense, person, or number]
        - uninflected [static or fixed regardless of tense, person, or subject agreement]
    - EXAMPLE: if we take the plural form disagreements, the form disagreement is called the stem.
        - inflected: -s
        - uninflected: disagreement
2. suffix: [[Lexicon of linguistics](https://lexicon.hum.uu.nl/) by Johan Kerstens, Eddy Ruys, Joost Zwarts]
    - MORPHOLOGY: a bound morpheme (or affix) which attaches at the righthand side of a base. 
    - EXAMPLE: the English morpheme -ness is a suffix, since it attaches to the right of adjectives (productiveness). 
        - inflected (of disagreements): -s

---

1. Strong verbs are ones that undergo a stem vowel change instead of suffixing to form pasts, like *sing*, *bite*, or *ride*.
    - sing: stem is sing + past form is sang,  $ \therefore $ the vowel change (i $ \rightarrow $ a).
    - bite: stem is bite + past form is bit.
    - ride: stem is ride + past form is rode,  $ \therefore $ the vowel change (i $ \rightarrow $ o).
2. Weak verbs are the ones that make pasts in -*ed* in English without any kind of stem change. These are regular in English.
    - predict: stem is predict + past form is predicted, $ \therefore $ the stem is without change + suffix change (-*ed*).
3. Semi-weak verbs both undergo stem change and suffixing a coronal obstruent (-*t* or -*d*) like sleep or tell. 
    - sleep: stem is sleep + past form is slept, $ \therefore $ the stem changes + suffix change (-*t*).
    - tell: stem is tell + past form is told, $ \therefore $ the stem changes + suffix change (-*d*).
4. Finally, suppletives are just straight-up irregulars like *go*.
    - go: stem is go + past form is went, $ \therefore $ the stem changes completely.

The terminology actually goes back to the Brothers Grimm. Mainly famous for their fairy tales, they were also foundational historical linguists and comparative Germanicists.

With the background information above, answer the following questions. For Question 2 and 3, you **may or may not** be using the en_ewt-ud-train.conllu file from the UD_EWT treebank as references to derive the past tense forms of some verbs.

1. How many types and tokens are in this data?

2. How many week (-*ed* past) verbs are in this data?

3. How many strong verbs are in this data?

4. Let’s say that this is the verbal lexicon of a young child (a child who only knows this many verbs must be quite young, maybe younger than two). For a child who knows exactly these verbs, is -*ed* productive?

> Answers are below with code

In [10]:
# Downloading an English dependency treebank
# !git clone https://github.com/UniversalDependencies/UD_English-EWT

In [11]:
# Insert your code here
import pandas as pd
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [12]:
data_path = '../data/sarah_brown.txt'
df = pd.read_csv(data_path, sep="\s+", header=None)
df.rename(columns={0: 'Frequency of Past Tense', 1: 'POS x Word x Tense'}, inplace=True)
df

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/var/folders/78/9z0b45fx1xqbwxh8vk97lcfh0000gn/T/ipykernel_83576/3109633024.py:2: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(data_path, sep="\s+", header=None)

     Frequency of Past Tense POS x Word x Tense
0                        123        v|have&past
1                        121         v|get&past
2                         87         v|say&past
3                         59          v|go&past
4                         40          v|do&past
5                         32       v|think&past
6                         26        v|give&past
7                         26        v|take&past
8                         23      v|happen-past
9                         22        v|tell&past
10                        18       v|leave&past
11                        17         v|buy&past
12                        17        v|come&past
13                        16        v|want-past
14                        12        v|know&past
15                        12        v|make&past
16                        11      v|forget&past
17                         8       v|start-past
18                         7        v|call-past
19                         7        v|find&past
20                         7        v|push-past
21                         6        v|fall&past
22                         6        v|look-past
23                         6        v|lose&past
24                         6         v|win&past
25                         5         v|ask-past
26                         5       v|break&past
27                         5       v|bring&past
28                         5        v|keep&past
29                         4       v|catch&past
30                         4        v|hear&past
31                         4         v|see&past
32                         4         v|sit&past
33                         4        v|stay-past
34                         3         v|die-past
35                         3        v|mean&past
36                         3         v|pay&past
37                         3        v|pick-past
38                         3        v|pull-past
39                         3         v|try-past
40                         3        v|walk-past
41                         3        v|wear&past
42                         3       v|write&past
43                         2        v|bite&past
44                         2       v|clean-past
45                         2       v|close-past
46                         2       v|drink&past
47                         2         v|eat&past
48                         2       v|fight&past
49                         2      v|figure-past
50                         2      v|finish-past
51                         2        v|fool-past
52                         2        v|jump-past
53                         2       v|knock-past
54                         2       v|learn-past
55                         2        v|live-past
56                         2        v|meet&past
57                         2        v|miss-past
58                         2        v|move-past
59                         2        v|name-past
60                         2        v|need-past
61                         2        v|open-past
62                         2        v|play-past
63                         2        v|show-past
64                         2       v|stick&past
65                         2       v|teach&past
66                         2        v|turn-past
67                         2        v|wake&past
68                         2        v|yell-past
69                         1        v|bang-past
70                         1        v|bawl-past
71                         1       v|blame-past
72                         1        v|bump-past
73                         1        v|calm-past
74                         1        v|cook-past
75                         1       v|cover-past
76                         1       v|crash-past
77                         1         v|cry-past
78                         1        v|curl-past
79                         1      v|decide-past
80                         1        v|drag-past
81                         1       v|dress-past
82                         1       v|drown-past
83                         1         v|dry-past
84                         1         v|end-past
85                         1        v|feed&past
86                         1         v|fix-past
87                         1         v|fly&past
88                         1        v|fold-past
89                         1        v|glue-past
90                         1        v|hide&past
91                         1        v|hold&past
92                         1     v|inherit-past
93                         1      v|insist-past
94                         1        v|lead&past
95                         1        v|lock-past
96                         1        v|pack-past
97                         1        v|park-past
98                         1       v|punch-past
99                         1        v|rain-past
100                        1    v|remember-past
101                        1      v|retire-past
102                        1        v|ride&past
103                        1        v|ring&past
104                        1         v|rip-past
105                        1      v|scream-past
106                        1        v|sing&past
107                        1       v|sleep&past
108                        1       v|spend&past
109                        1     v|squoosh-past
110                        1        v|talk-past
111                        1       v|throw&past
112                        1         v|tie-past
113                        1        v|tire-past
114                        1        v|wash-past
115                        1       v|watch-past
116                        1      v|wonder-past
117                        1        v|work-past
118                        1        v|wrap-past

1. How many types and tokens are in this data?

In [13]:
df.loc[:, 'Frequency of Past Tense'].sum()

np.int64(884)

## Weak x Strong Verbs

In [14]:
# df.loc[:, 'POS x Word x Tense']
pos_tags = []
words = []
tenses = []

for idx, row in df.iterrows():
    raw_pos_word_tense = row['POS x Word x Tense']
    print(f"Raw ({idx}): {raw_pos_word_tense}")

    separate_pos = raw_pos_word_tense.split('|')
    print(f" -> Separate: {separate_pos}")

    pos = separate_pos[0]
    print(f"  -> pos: {pos}")
    pos_tags.append(pos)

    word_and_tense = separate_pos[1]
    separator = '&' if '&' in word_and_tense else '-'
    separate_word_and_tense = word_and_tense.split(separator)
    word = separate_word_and_tense[0]
    tense = separate_word_and_tense[1]
    print(f"  -> word: {word} \n  -> tense {tense}")
    words.append(word)
    tenses.append(tense)
    print()

df['POS'] = pos_tags
df['Words'] = words
df['Tenses'] = tenses

df

Raw (0): v|have&past
 -> Separate: ['v', 'have&past']
  -> pos: v
  -> word: have
  -> tense past

Raw (1): v|get&past
 -> Separate: ['v', 'get&past']
  -> pos: v
  -> word: get
  -> tense past

Raw (2): v|say&past
 -> Separate: ['v', 'say&past']
  -> pos: v
  -> word: say
  -> tense past

Raw (3): v|go&past
 -> Separate: ['v', 'go&past']
  -> pos: v
  -> word: go
  -> tense past

Raw (4): v|do&past
 -> Separate: ['v', 'do&past']
  -> pos: v
  -> word: do
  -> tense past

Raw (5): v|think&past
 -> Separate: ['v', 'think&past']
  -> pos: v
  -> word: think
  -> tense past

Raw (6): v|give&past
 -> Separate: ['v', 'give&past']
  -> pos: v
  -> word: give
  -> tense past

Raw (7): v|take&past
 -> Separate: ['v', 'take&past']
  -> pos: v
  -> word: take
  -> tense past

Raw (8): v|happen-past
 -> Separate: ['v', 'happen-past']
  -> pos: v
  -> word: happen
  -> tense past

Raw (9): v|tell&past
 -> Separate: ['v', 'tell&past']
  -> pos: v
  -> word: tell
  -> tense past

Raw (10): v|leave&past
 -> Separate: ['v', 'leave&past']
  -> pos: v
  -> word: leave
  -> tense past

Raw (11): v|buy&past
 -> Separate: ['v', 'buy&past']
  -> pos: v
  -> word: buy
  -> tense past

Raw (12): v|come&past
 -> Separate: ['v', 'come&past']
  -> pos: v
  -> word: come
  -> tense past

Raw (13): v|want-past
 -> Separate: ['v', 'want-past']
  -> pos: v
  -> word: want
  -> tense past

Raw (14): v|know&past
 -> Separate: ['v', 'know&past']
  -> pos: v
  -> word: know
  -> tense past

Raw (15): v|make&past
 -> Separate: ['v', 'make&past']
  -> pos: v
  -> word: make
  -> tense past

Raw (16): v|forget&past
 -> Separate: ['v', 'forget&past']
  -> pos: v
  -> word: forget
  -> tense past

Raw (17): v|start-past
 -> Separate: ['v', 'start-past']
  -> pos: v
  -> word: start
  -> tense past

Raw (18): v|call-past
 -> Separate: ['v', 'call-past']
  -> pos: v
  -> word: call
  -> tense past

Raw (19): v|find&past
 -> Separate: ['v', 'find&past']
  -> pos: v
  -> word: find
  -> tense past

Raw (20): v|push-past
 -> Separate: ['v', 'push-past']
  -> pos: v
  -> word: push
  -> tense past

Raw (21): v|fall&past
 -> Separate: ['v', 'fall&past']
  -> pos: v
  -> word: fall
  -> tense past

Raw (22): v|look-past
 -> Separate: ['v', 'look-past']
  -> pos: v
  -> word: look
  -> tense past

Raw (23): v|lose&past
 -> Separate: ['v', 'lose&past']
  -> pos: v
  -> word: lose
  -> tense past

Raw (24): v|win&past
 -> Separate: ['v', 'win&past']
  -> pos: v
  -> word: win
  -> tense past

Raw (25): v|ask-past
 -> Separate: ['v', 'ask-past']
  -> pos: v
  -> word: ask
  -> tense past

Raw (26): v|break&past
 -> Separate: ['v', 'break&past']
  -> pos: v
  -> word: break
  -> tense past

Raw (27): v|bring&past
 -> Separate: ['v', 'bring&past']
  -> pos: v
  -> word: bring
  -> tense past

Raw (28): v|keep&past
 -> Separate: ['v', 'keep&past']
  -> pos: v
  -> word: keep
  -> tense past

Raw (29): v|catch&past
 -> Separate: ['v', 'catch&past']
  -> pos: v
  -> word: catch
  -> tense past

Raw (30): v|hear&past
 -> Separate: ['v', 'hear&past']
  -> pos: v
  -> word: hear
  -> tense past

Raw (31): v|see&past
 -> Separate: ['v', 'see&past']
  -> pos: v
  -> word: see
  -> tense past

Raw (32): v|sit&past
 -> Separate: ['v', 'sit&past']
  -> pos: v
  -> word: sit
  -> tense past

Raw (33): v|stay-past
 -> Separate: ['v', 'stay-past']
  -> pos: v
  -> word: stay
  -> tense past

Raw (34): v|die-past
 -> Separate: ['v', 'die-past']
  -> pos: v
  -> word: die
  -> tense past

Raw (35): v|mean&past
 -> Separate: ['v', 'mean&past']
  -> pos: v
  -> word: mean
  -> tense past

Raw (36): v|pay&past
 -> Separate: ['v', 'pay&past']
  -> pos: v
  -> word: pay
  -> tense past

Raw (37): v|pick-past
 -> Separate: ['v', 'pick-past']
  -> pos: v
  -> word: pick
  -> tense past

Raw (38): v|pull-past
 -> Separate: ['v', 'pull-past']
  -> pos: v
  -> word: pull
  -> tense past

Raw (39): v|try-past
 -> Separate: ['v', 'try-past']
  -> pos: v
  -> word: try
  -> tense past

Raw (40): v|walk-past
 -> Separate: ['v', 'walk-past']
  -> pos: v
  -> word: walk
  -> tense past

Raw (41): v|wear&past
 -> Separate: ['v', 'wear&past']
  -> pos: v
  -> word: wear
  -> tense past

Raw (42): v|write&past
 -> Separate: ['v', 'write&past']
  -> pos: v
  -> word: write
  -> tense past

Raw (43): v|bite&past
 -> Separate: ['v', 'bite&past']
  -> pos: v
  -> word: bite
  -> tense past

Raw (44): v|clean-past
 -> Separate: ['v', 'clean-past']
  -> pos: v
  -> word: clean
  -> tense past

Raw (45): v|close-past
 -> Separate: ['v', 'close-past']
  -> pos: v
  -> word: close
  -> tense past

Raw (46): v|drink&past
 -> Separate: ['v', 'drink&past']
  -> pos: v
  -> word: drink
  -> tense past

Raw (47): v|eat&past
 -> Separate: ['v', 'eat&past']
  -> pos: v
  -> word: eat
  -> tense past

Raw (48): v|fight&past
 -> Separate: ['v', 'fight&past']
  -> pos: v
  -> word: fight
  -> tense past

Raw (49): v|figure-past
 -> Separate: ['v', 'figure-past']
  -> pos: v
  -> word: figure
  -> tense past

Raw (50): v|finish-past
 -> Separate: ['v', 'finish-past']
  -> pos: v
  -> word: finish
  -> tense past

Raw (51): v|fool-past
 -> Separate: ['v', 'fool-past']
  -> pos: v
  -> word: fool
  -> tense past

Raw (52): v|jump-past
 -> Separate: ['v', 'jump-past']
  -> pos: v
  -> word: jump
  -> tense past

Raw (53): v|knock-past
 -> Separate: ['v', 'knock-past']
  -> pos: v
  -> word: knock
  -> tense past

Raw (54): v|learn-past
 -> Separate: ['v', 'learn-past']
  -> pos: v
  -> word: learn
  -> tense past

Raw (55): v|live-past
 -> Separate: ['v', 'live-past']
  -> pos: v
  -> word: live
  -> tense past

Raw (56): v|meet&past
 -> Separate: ['v', 'meet&past']
  -> pos: v
  -> word: meet
  -> tense past

Raw (57): v|miss-past
 -> Separate: ['v', 'miss-past']
  -> pos: v
  -> word: miss
  -> tense past

Raw (58): v|move-past
 -> Separate: ['v', 'move-past']
  -> pos: v
  -> word: move
  -> tense past

Raw (59): v|name-past
 -> Separate: ['v', 'name-past']
  -> pos: v
  -> word: name
  -> tense past

Raw (60): v|need-past
 -> Separate: ['v', 'need-past']
  -> pos: v
  -> word: need
  -> tense past

Raw (61): v|open-past
 -> Separate: ['v', 'open-past']
  -> pos: v
  -> word: open
  -> tense past

Raw (62): v|play-past
 -> Separate: ['v', 'play-past']
  -> pos: v
  -> word: play
  -> tense past

Raw (63): v|show-past
 -> Separate: ['v', 'show-past']
  -> pos: v
  -> word: show
  -> tense past

Raw (64): v|stick&past
 -> Separate: ['v', 'stick&past']
  -> pos: v
  -> word: stick
  -> tense past

Raw (65): v|teach&past
 -> Separate: ['v', 'teach&past']
  -> pos: v
  -> word: teach
  -> tense past

Raw (66): v|turn-past
 -> Separate: ['v', 'turn-past']
  -> pos: v
  -> word: turn
  -> tense past

Raw (67): v|wake&past
 -> Separate: ['v', 'wake&past']
  -> pos: v
  -> word: wake
  -> tense past

Raw (68): v|yell-past
 -> Separate: ['v', 'yell-past']
  -> pos: v
  -> word: yell
  -> tense past

Raw (69): v|bang-past
 -> Separate: ['v', 'bang-past']
  -> pos: v
  -> word: bang
  -> tense past

Raw (70): v|bawl-past
 -> Separate: ['v', 'bawl-past']
  -> pos: v
  -> word: bawl
  -> tense past

Raw (71): v|blame-past
 -> Separate: ['v', 'blame-past']
  -> pos: v
  -> word: blame
  -> tense past

Raw (72): v|bump-past
 -> Separate: ['v', 'bump-past']
  -> pos: v
  -> word: bump
  -> tense past

Raw (73): v|calm-past
 -> Separate: ['v', 'calm-past']
  -> pos: v
  -> word: calm
  -> tense past

Raw (74): v|cook-past
 -> Separate: ['v', 'cook-past']
  -> pos: v
  -> word: cook
  -> tense past

Raw (75): v|cover-past
 -> Separate: ['v', 'cover-past']
  -> pos: v
  -> word: cover
  -> tense past

Raw (76): v|crash-past
 -> Separate: ['v', 'crash-past']
  -> pos: v
  -> word: crash
  -> tense past

Raw (77): v|cry-past
 -> Separate: ['v', 'cry-past']
  -> pos: v
  -> word: cry
  -> tense past

Raw (78): v|curl-past
 -> Separate: ['v', 'curl-past']
  -> pos: v
  -> word: curl
  -> tense past

Raw (79): v|decide-past
 -> Separate: ['v', 'decide-past']
  -> pos: v
  -> word: decide
  -> tense past

Raw (80): v|drag-past
 -> Separate: ['v', 'drag-past']
  -> pos: v
  -> word: drag
  -> tense past

Raw (81): v|dress-past
 -> Separate: ['v', 'dress-past']
  -> pos: v
  -> word: dress
  -> tense past

Raw (82): v|drown-past
 -> Separate: ['v', 'drown-past']
  -> pos: v
  -> word: drown
  -> tense past

Raw (83): v|dry-past
 -> Separate: ['v', 'dry-past']
  -> pos: v
  -> word: dry
  -> tense past

Raw (84): v|end-past
 -> Separate: ['v', 'end-past']
  -> pos: v
  -> word: end
  -> tense past

Raw (85): v|feed&past
 -> Separate: ['v', 'feed&past']
  -> pos: v
  -> word: feed
  -> tense past

Raw (86): v|fix-past
 -> Separate: ['v', 'fix-past']
  -> pos: v
  -> word: fix
  -> tense past

Raw (87): v|fly&past
 -> Separate: ['v', 'fly&past']
  -> pos: v
  -> word: fly
  -> tense past

Raw (88): v|fold-past
 -> Separate: ['v', 'fold-past']
  -> pos: v
  -> word: fold
  -> tense past

Raw (89): v|glue-past
 -> Separate: ['v', 'glue-past']
  -> pos: v
  -> word: glue
  -> tense past

Raw (90): v|hide&past
 -> Separate: ['v', 'hide&past']
  -> pos: v
  -> word: hide
  -> tense past

Raw (91): v|hold&past
 -> Separate: ['v', 'hold&past']
  -> pos: v
  -> word: hold
  -> tense past

Raw (92): v|inherit-past
 -> Separate: ['v', 'inherit-past']
  -> pos: v
  -> word: inherit
  -> tense past

Raw (93): v|insist-past
 -> Separate: ['v', 'insist-past']
  -> pos: v
  -> word: insist
  -> tense past

Raw (94): v|lead&past
 -> Separate: ['v', 'lead&past']
  -> pos: v
  -> word: lead
  -> tense past

Raw (95): v|lock-past
 -> Separate: ['v', 'lock-past']
  -> pos: v
  -> word: lock
  -> tense past

Raw (96): v|pack-past
 -> Separate: ['v', 'pack-past']
  -> pos: v
  -> word: pack
  -> tense past

Raw (97): v|park-past
 -> Separate: ['v', 'park-past']
  -> pos: v
  -> word: park
  -> tense past

Raw (98): v|punch-past
 -> Separate: ['v', 'punch-past']
  -> pos: v
  -> word: punch
  -> tense past

Raw (99): v|rain-past
 -> Separate: ['v', 'rain-past']
  -> pos: v
  -> word: rain
  -> tense past

Raw (100): v|remember-past
 -> Separate: ['v', 'remember-past']
  -> pos: v
  -> word: remember
  -> tense past

Raw (101): v|retire-past
 -> Separate: ['v', 'retire-past']
  -> pos: v
  -> word: retire
  -> tense past

Raw (102): v|ride&past
 -> Separate: ['v', 'ride&past']
  -> pos: v
  -> word: ride
  -> tense past

Raw (103): v|ring&past
 -> Separate: ['v', 'ring&past']
  -> pos: v
  -> word: ring
  -> tense past

Raw (104): v|rip-past
 -> Separate: ['v', 'rip-past']
  -> pos: v
  -> word: rip
  -> tense past

Raw (105): v|scream-past
 -> Separate: ['v', 'scream-past']
  -> pos: v
  -> word: scream
  -> tense past

Raw (106): v|sing&past
 -> Separate: ['v', 'sing&past']
  -> pos: v
  -> word: sing
  -> tense past

Raw (107): v|sleep&past
 -> Separate: ['v', 'sleep&past']
  -> pos: v
  -> word: sleep
  -> tense past

Raw (108): v|spend&past
 -> Separate: ['v', 'spend&past']
  -> pos: v
  -> word: spend
  -> tense past

Raw (109): v|squoosh-past
 -> Separate: ['v', 'squoosh-past']
  -> pos: v
  -> word: squoosh
  -> tense past

Raw (110): v|talk-past
 -> Separate: ['v', 'talk-past']
  -> pos: v
  -> word: talk
  -> tense past

Raw (111): v|throw&past
 -> Separate: ['v', 'throw&past']
  -> pos: v
  -> word: throw
  -> tense past

Raw (112): v|tie-past
 -> Separate: ['v', 'tie-past']
  -> pos: v
  -> word: tie
  -> tense past

Raw (113): v|tire-past
 -> Separate: ['v', 'tire-past']
  -> pos: v
  -> word: tire
  -> tense past

Raw (114): v|wash-past
 -> Separate: ['v', 'wash-past']
  -> pos: v
  -> word: wash
  -> tense past

Raw (115): v|watch-past
 -> Separate: ['v', 'watch-past']
  -> pos: v
  -> word: watch
  -> tense past

Raw (116): v|wonder-past
 -> Separate: ['v', 'wonder-past']
  -> pos: v
  -> word: wonder
  -> tense past

Raw (117): v|work-past
 -> Separate: ['v', 'work-past']
  -> pos: v
  -> word: work
  -> tense past

Raw (118): v|wrap-past
 -> Separate: ['v', 'wrap-past']
  -> pos: v
  -> word: wrap
  -> tense past

     Frequency of Past Tense POS x Word x Tense POS     Words Tenses
0                        123        v|have&past   v      have   past
1                        121         v|get&past   v       get   past
2                         87         v|say&past   v       say   past
3                         59          v|go&past   v        go   past
4                         40          v|do&past   v        do   past
5                         32       v|think&past   v     think   past
6                         26        v|give&past   v      give   past
7                         26        v|take&past   v      take   past
8                         23      v|happen-past   v    happen   past
9                         22        v|tell&past   v      tell   past
10                        18       v|leave&past   v     leave   past
11                        17         v|buy&past   v       buy   past
12                        17        v|come&past   v      come   past
13                        16        v|want-past   v      want   past
14                        12        v|know&past   v      know   past
15                        12        v|make&past   v      make   past
16                        11      v|forget&past   v    forget   past
17                         8       v|start-past   v     start   past
18                         7        v|call-past   v      call   past
19                         7        v|find&past   v      find   past
20                         7        v|push-past   v      push   past
21                         6        v|fall&past   v      fall   past
22                         6        v|look-past   v      look   past
23                         6        v|lose&past   v      lose   past
24                         6         v|win&past   v       win   past
25                         5         v|ask-past   v       ask   past
26                         5       v|break&past   v     break   past
27                         5       v|bring&past   v     bring   past
28                         5        v|keep&past   v      keep   past
29                         4       v|catch&past   v     catch   past
30                         4        v|hear&past   v      hear   past
31                         4         v|see&past   v       see   past
32                         4         v|sit&past   v       sit   past
33                         4        v|stay-past   v      stay   past
34                         3         v|die-past   v       die   past
35                         3        v|mean&past   v      mean   past
36                         3         v|pay&past   v       pay   past
37                         3        v|pick-past   v      pick   past
38                         3        v|pull-past   v      pull   past
39                         3         v|try-past   v       try   past
40                         3        v|walk-past   v      walk   past
41                         3        v|wear&past   v      wear   past
42                         3       v|write&past   v     write   past
43                         2        v|bite&past   v      bite   past
44                         2       v|clean-past   v     clean   past
45                         2       v|close-past   v     close   past
46                         2       v|drink&past   v     drink   past
47                         2         v|eat&past   v       eat   past
48                         2       v|fight&past   v     fight   past
49                         2      v|figure-past   v    figure   past
50                         2      v|finish-past   v    finish   past
51                         2        v|fool-past   v      fool   past
52                         2        v|jump-past   v      jump   past
53                         2       v|knock-past   v     knock   past
54                         2       v|learn-past   v     learn   past
55                         2        v|live-past   v      live   past
56                         2        v|meet&past   v      meet   past
57                         2        v|miss-past   v      miss   past
58                         2        v|move-past   v      move   past
59                         2        v|name-past   v      name   past
60                         2        v|need-past   v      need   past
61                         2        v|open-past   v      open   past
62                         2        v|play-past   v      play   past
63                         2        v|show-past   v      show   past
64                         2       v|stick&past   v     stick   past
65                         2       v|teach&past   v     teach   past
66                         2        v|turn-past   v      turn   past
67                         2        v|wake&past   v      wake   past
68                         2        v|yell-past   v      yell   past
69                         1        v|bang-past   v      bang   past
70                         1        v|bawl-past   v      bawl   past
71                         1       v|blame-past   v     blame   past
72                         1        v|bump-past   v      bump   past
73                         1        v|calm-past   v      calm   past
74                         1        v|cook-past   v      cook   past
75                         1       v|cover-past   v     cover   past
76                         1       v|crash-past   v     crash   past
77                         1         v|cry-past   v       cry   past
78                         1        v|curl-past   v      curl   past
79                         1      v|decide-past   v    decide   past
80                         1        v|drag-past   v      drag   past
81                         1       v|dress-past   v     dress   past
82                         1       v|drown-past   v     drown   past
83                         1         v|dry-past   v       dry   past
84                         1         v|end-past   v       end   past
85                         1        v|feed&past   v      feed   past
86                         1         v|fix-past   v       fix   past
87                         1         v|fly&past   v       fly   past
88                         1        v|fold-past   v      fold   past
89                         1        v|glue-past   v      glue   past
90                         1        v|hide&past   v      hide   past
91                         1        v|hold&past   v      hold   past
92                         1     v|inherit-past   v   inherit   past
93                         1      v|insist-past   v    insist   past
94                         1        v|lead&past   v      lead   past
95                         1        v|lock-past   v      lock   past
96                         1        v|pack-past   v      pack   past
97                         1        v|park-past   v      park   past
98                         1       v|punch-past   v     punch   past
99                         1        v|rain-past   v      rain   past
100                        1    v|remember-past   v  remember   past
101                        1      v|retire-past   v    retire   past
102                        1        v|ride&past   v      ride   past
103                        1        v|ring&past   v      ring   past
104                        1         v|rip-past   v       rip   past
105                        1      v|scream-past   v    scream   past
106                        1        v|sing&past   v      sing   past
107                        1       v|sleep&past   v     sleep   past
108                        1       v|spend&past   v     spend   past
109                        1     v|squoosh-past   v   squoosh   past
110                        1        v|talk-past   v      talk   past
111                        1       v|throw&past   v     throw   past
112                        1         v|tie-past   v       tie   past
113                        1        v|tire-past   v      tire   past
114                        1        v|wash-past   v      wash   past
115                        1       v|watch-past   v     watch   past
116                        1      v|wonder-past   v    wonder   past
117                        1        v|work-past   v      work   past
118                        1        v|wrap-past   v      wrap   past

In [15]:
words = df.loc[:, 'Words'].to_list()
words

['have',
 'get',
 'say',
 'go',
 'do',
 'think',
 'give',
 'take',
 'happen',
 'tell',
 'leave',
 'buy',
 'come',
 'want',
 'know',
 'make',
 'forget',
 'start',
 'call',
 'find',
 'push',
 'fall',
 'look',
 'lose',
 'win',
 'ask',
 'break',
 'bring',
 'keep',
 'catch',
 'hear',
 'see',
 'sit',
 'stay',
 'die',
 'mean',
 'pay',
 'pick',
 'pull',
 'try',
 'walk',
 'wear',
 'write',
 'bite',
 'clean',
 'close',
 'drink',
 'eat',
 'fight',
 'figure',
 'finish',
 'fool',
 'jump',
 'knock',
 'learn',
 'live',
 'meet',
 'miss',
 'move',
 'name',
 'need',
 'open',
 'play',
 'show',
 'stick',
 'teach',
 'turn',
 'wake',
 'yell',
 'bang',
 'bawl',
 'blame',
 'bump',
 'calm',
 'cook',
 'cover',
 'crash',
 'cry',
 'curl',
 'decide',
 'drag',
 'dress',
 'drown',
 'dry',
 'end',
 'feed',
 'fix',
 'fly',
 'fold',
 'glue',
 'hide',
 'hold',
 'inherit',
 'insist',
 'lead',
 'lock',
 'pack',
 'park',
 'punch',
 'rain',
 'remember',
 'retire',
 'ride',
 'ring',
 'rip',
 'scream',
 'sing',
 'sleep',
 'spend',
 'squoosh',
 'talk',
 'throw',
 'tie',
 'tire',
 'wash',
 'watch',
 'wonder',
 'work',
 'wrap']

In [16]:
from lemminflect import getInflection
get_past_tenses = []

for word in words:
    get_past_tense = getInflection(word, tag="VBD")[0]
    get_past_tenses.append(get_past_tense)

df['Past Tense Word'] = get_past_tenses
df

,Frequency of Past Tense,POS x Word x Tense,POS,Words,Tenses,Past Tense Word
0,123,v|have&past,v,have,past,had
1,121,v|get&past,v,get,past,got
2,87,v|say&past,v,say,past,said
3,59,v|go&past,v,go,past,went
4,40,v|do&past,v,do,past,did
5,32,v|think&past,v,think,past,thought
6,26,v|give&past,v,give,past,gave
7,26,v|take&past,v,take,past,took
8,23,v|happen-past,v,happen,past,happened
9,22,v|tell&past,v,tell,past,told
10,18,v|leave&past,v,leave,past,left
11,17,v|buy&past,v,buy,past,bought
12,17,v|come&past,v,come,past,came
13,16,v|want-past,v,want,past,wanted
14,12,v|know&past,v,know,past,knew
15,12,v|make&past,v,make,past,made
16,11,v|forget&past,v,forget,past,forgot
17,8,v|start-past,v,start,past,started
18,7,v|call-past,v,call,past,called
19,7,v|find&past,v,find,past,found
20,7,v|push-past,v,push,past,pushed
21,6,v|fall&past,v,fall,past,fell
22,6,v|look-past,v,look,past,looked
23,6,v|lose&past,v,lose,past,lost
24,6,v|win&past,v,win,past,won
25,5,v|ask-past,v,ask,past,asked
26,5,v|break&past,v,break,past,broke
27,5,v|bring&past,v,bring,past,brought
28,5,v|keep&past,v,keep,past,kept
29,4,v|catch&past,v,catch,past,caught
30,4,v|hear&past,v,hear,past,heard
31,4,v|see&past,v,see,past,saw
32,4,v|sit&past,v,sit,past,sat
33,4,v|stay-past,v,stay,past,stayed
34,3,v|die-past,v,die,past,died
35,3,v|mean&past,v,mean,past,meant
36,3,v|pay&past,v,pay,past,paid
37,3,v|pick-past,v,pick,past,picked
38,3,v|pull-past,v,pull,past,pulled
39,3,v|try-past,v,try,past,tried
40,3,v|walk-past,v,walk,past,walked
41,3,v|wear&past,v,wear,past,wore
42,3,v|write&past,v,write,past,wrote
43,2,v|bite&past,v,bite,past,bit
44,2,v|clean-past,v,clean,past,cleaned
45,2,v|close-past,v,close,past,closed
46,2,v|drink&past,v,drink,past,drank
47,2,v|eat&past,v,eat,past,ate
48,2,v|fight&past,v,fight,past,fought
49,2,v|figure-past,v,figure,past,figured
50,2,v|finish-past,v,finish,past,finished
51,2,v|fool-past,v,fool,past,fooled
52,2,v|jump-past,v,jump,past,jumped
53,2,v|knock-past,v,knock,past,knocked
54,2,v|learn-past,v,learn,past,learned
55,2,v|live-past,v,live,past,lived
56,2,v|meet&past,v,meet,past,met
57,2,v|miss-past,v,miss,past,missed
58,2,v|move-past,v,move,past,moved
59,2,v|name-past,v,name,past,named
60,2,v|need-past,v,need,past,needed
61,2,v|open-past,v,open,past,opened
62,2,v|play-past,v,play,past,played
63,2,v|show-past,v,show,past,showed
64,2,v|stick&past,v,stick,past,stuck
65,2,v|teach&past,v,teach,past,taught
66,2,v|turn-past,v,turn,past,turned
67,2,v|wake&past,v,wake,past,woke
68,2,v|yell-past,v,yell,past,yelled
69,1,v|bang-past,v,bang,past,banged
70,1,v|bawl-past,v,bawl,past,bawled
71,1,v|blame-past,v,blame,past,blamed
72,1,v|bump-past,v,bump,past,bumped
73,1,v|calm-past,v,calm,past,calmed
74,1,v|cook-past,v,cook,past,cooked
75,1,v|cover-past,v,cover,past,covered
76,1,v|crash-past,v,crash,past,crashed
77,1,v|cry-past,v,cry,past,cried
78,1,v|curl-past,v,curl,past,curled
79,1,v|decide-past,v,decide,past,decided
80,1,v|drag-past,v,drag,past,dragged
81,1,v|dress-past,v,dress,past,dressed
82,1,v|drown-past,v,drown,past,drowned
83,1,v|dry-past,v,dry,past,dried
84,1,v|end-past,v,end,past,ended
85,1,v|feed&past,v,feed,past,fed
86,1,v|fix-past,v,fix,past,fixed
87,1,v|fly&past,v,fly,past,flew
88,1,v|fold-past,v,fold,past,folded
89,1,v|glue-past,v,glue,past,glued
90,1,v|hide&past,v,hide,past,hid
91,1,v|hold&past,v,hold,past,held
92,1,v|inherit-past,v,inherit,past,inherited
93,1,v|insist-past,v,insist,past,insisted
94,1,v|lead&past,v,lead,past,led
95,1,v|lock-past,v,lock,past,locked
96,1,v|pack-past,v,pack,past,packed
97,1,v|park-past,v,park,past,parked
98,1,v|punch-past,v,punch,past,punched
99,1,v|rain-past,v,rain,past,rained
100,1,v|remember-past,v,remember,past,remembered
101,1,v|retire-past,v,retire,past,retired
102,1,v|ride&past,v,ride,past,rode
103,1,v|ring&past,v,ring,past,rang
104,1,v|rip-past,v,rip,past,ripped
105,1,v|scream-past,v,scream,past,screamed
106,1,v|sing&past,v,sing,past,sang
107,1,v|sleep&past,v,sleep,past,slept
108,1,v|spend&past,v,spend,past,spent
109,1,v|squoosh-past,v,squoosh,past,squooshed
110,1,v|talk-past,v,talk,past,talked
111,1,v|throw&past,v,throw,past,threw
112,1,v|tie-past,v,tie,past,tied
113,1,v|tire-past,v,tire,past,tired
114,1,v|wash-past,v,wash,past,washed
115,1,v|watch-past,v,watch,past,watched
116,1,v|wonder-past,v,wonder,past,wondered
117,1,v|work-past,v,work,past,worked
118,1,v|wrap-past,v,wrap,past,wrapped

In [17]:
past_tense_words = df.loc[:, 'Past Tense Word'].to_list()
past_tense_words

['had',
 'got',
 'said',
 'went',
 'did',
 'thought',
 'gave',
 'took',
 'happened',
 'told',
 'left',
 'bought',
 'came',
 'wanted',
 'knew',
 'made',
 'forgot',
 'started',
 'called',
 'found',
 'pushed',
 'fell',
 'looked',
 'lost',
 'won',
 'asked',
 'broke',
 'brought',
 'kept',
 'caught',
 'heard',
 'saw',
 'sat',
 'stayed',
 'died',
 'meant',
 'paid',
 'picked',
 'pulled',
 'tried',
 'walked',
 'wore',
 'wrote',
 'bit',
 'cleaned',
 'closed',
 'drank',
 'ate',
 'fought',
 'figured',
 'finished',
 'fooled',
 'jumped',
 'knocked',
 'learned',
 'lived',
 'met',
 'missed',
 'moved',
 'named',
 'needed',
 'opened',
 'played',
 'showed',
 'stuck',
 'taught',
 'turned',
 'woke',
 'yelled',
 'banged',
 'bawled',
 'blamed',
 'bumped',
 'calmed',
 'cooked',
 'covered',
 'crashed',
 'cried',
 'curled',
 'decided',
 'dragged',
 'dressed',
 'drowned',
 'dried',
 'ended',
 'fed',
 'fixed',
 'flew',
 'folded',
 'glued',
 'hid',
 'held',
 'inherited',
 'insisted',
 'led',
 'locked',
 'packed',
 'parked',
 'punched',
 'rained',
 'remembered',
 'retired',
 'rode',
 'rang',
 'ripped',
 'screamed',
 'sang',
 'slept',
 'spent',
 'squooshed',
 'talked',
 'threw',
 'tied',
 'tired',
 'washed',
 'watched',
 'wondered',
 'worked',
 'wrapped']

2. How many week (-*ed* past) verbs are in this data?

> 72

- predict: stem is predict + past form is predicted, $ \therefore $ the stem is without change + suffix change (-*ed*).

In [29]:
get_weak_verbs = []
get_other_verbs = []

for past_tense_word in past_tense_words:
    if past_tense_word.endswith("ed"):
        get_weak_verbs.append(past_tense_word)
    else:
        get_other_verbs.append(past_tense_word)
get_weak_verbs

['happened',
 'wanted',
 'started',
 'called',
 'pushed',
 'looked',
 'asked',
 'stayed',
 'died',
 'picked',
 'pulled',
 'tried',
 'walked',
 'cleaned',
 'closed',
 'figured',
 'finished',
 'fooled',
 'jumped',
 'knocked',
 'learned',
 'lived',
 'missed',
 'moved',
 'named',
 'needed',
 'opened',
 'played',
 'showed',
 'turned',
 'yelled',
 'banged',
 'bawled',
 'blamed',
 'bumped',
 'calmed',
 'cooked',
 'covered',
 'crashed',
 'cried',
 'curled',
 'decided',
 'dragged',
 'dressed',
 'drowned',
 'dried',
 'ended',
 'fed',
 'fixed',
 'folded',
 'glued',
 'inherited',
 'insisted',
 'led',
 'locked',
 'packed',
 'parked',
 'punched',
 'rained',
 'remembered',
 'retired',
 'ripped',
 'screamed',
 'squooshed',
 'talked',
 'tied',
 'tired',
 'washed',
 'watched',
 'wondered',
 'worked',
 'wrapped']

In [28]:
len(get_weak_verbs)

72

3. How many strong verbs are in this data? 

> 28

- undergo a stem vowel change instead of suffixing to form pasts, like *sing*, *bite*, or *ride*.
    - sing: stem is sing + past form is sang,  $ \therefore $ the vowel change (i $ \rightarrow $ a).
    - bite: stem is bite + past form is bit.
    - ride: stem is ride + past form is rode,  $ \therefore $ the vowel change (i $ \rightarrow $ o).

In [30]:
get_other_verbs

['had',
 'got',
 'said',
 'went',
 'did',
 'thought',
 'gave',
 'took',
 'told',
 'left',
 'bought',
 'came',
 'knew',
 'made',
 'forgot',
 'found',
 'fell',
 'lost',
 'won',
 'broke',
 'brought',
 'kept',
 'caught',
 'heard',
 'saw',
 'sat',
 'meant',
 'paid',
 'wore',
 'wrote',
 'bit',
 'drank',
 'ate',
 'fought',
 'met',
 'stuck',
 'taught',
 'woke',
 'flew',
 'hid',
 'held',
 'rode',
 'rang',
 'sang',
 'slept',
 'spent',
 'threw']

In [33]:
non_ed_dfs = []

for get_other_verb in get_other_verbs:
    filt_non_ed = (df.loc[:, 'Past Tense Word'] == get_other_verb)
    non_ed_df = df[filt_non_ed]
    non_ed_dfs.append(non_ed_df)

non_ed_df = pd.concat(non_ed_dfs)
non_ed_df

,Frequency of Past Tense,POS x Word x Tense,POS,Words,Tenses,Past Tense Word
0,123,v|have&past,v,have,past,had
1,121,v|get&past,v,get,past,got
2,87,v|say&past,v,say,past,said
3,59,v|go&past,v,go,past,went
4,40,v|do&past,v,do,past,did
5,32,v|think&past,v,think,past,thought
6,26,v|give&past,v,give,past,gave
7,26,v|take&past,v,take,past,took
9,22,v|tell&past,v,tell,past,told
10,18,v|leave&past,v,leave,past,left
11,17,v|buy&past,v,buy,past,bought
12,17,v|come&past,v,come,past,came
14,12,v|know&past,v,know,past,knew
15,12,v|make&past,v,make,past,made
16,11,v|forget&past,v,forget,past,forgot
19,7,v|find&past,v,find,past,found
21,6,v|fall&past,v,fall,past,fell
23,6,v|lose&past,v,lose,past,lost
24,6,v|win&past,v,win,past,won
26,5,v|break&past,v,break,past,broke
27,5,v|bring&past,v,bring,past,brought
28,5,v|keep&past,v,keep,past,kept
29,4,v|catch&past,v,catch,past,caught
30,4,v|hear&past,v,hear,past,heard
31,4,v|see&past,v,see,past,saw
32,4,v|sit&past,v,sit,past,sat
35,3,v|mean&past,v,mean,past,meant
36,3,v|pay&past,v,pay,past,paid
41,3,v|wear&past,v,wear,past,wore
42,3,v|write&past,v,write,past,wrote
43,2,v|bite&past,v,bite,past,bit
46,2,v|drink&past,v,drink,past,drank
47,2,v|eat&past,v,eat,past,ate
48,2,v|fight&past,v,fight,past,fought
56,2,v|meet&past,v,meet,past,met
64,2,v|stick&past,v,stick,past,stuck
65,2,v|teach&past,v,teach,past,taught
67,2,v|wake&past,v,wake,past,woke
87,1,v|fly&past,v,fly,past,flew
90,1,v|hide&past,v,hide,past,hid
91,1,v|hold&past,v,hold,past,held
102,1,v|ride&past,v,ride,past,rode
103,1,v|ring&past,v,ring,past,rang
106,1,v|sing&past,v,sing,past,sang
107,1,v|sleep&past,v,sleep,past,slept
108,1,v|spend&past,v,spend,past,spent
111,1,v|throw&past,v,throw,past,threw

In [35]:
strong_verbs_df = non_ed_df.loc[[0, 1, 5, 6, 7, 11, 12, 14, 15, 16, 21, 24, 26, 32, 35, 42, 43, 46, 56, 64, 65, 67, 87, 90, 102, 103, 106, 111], :]
strong_verbs_df

,Frequency of Past Tense,POS x Word x Tense,POS,Words,Tenses,Past Tense Word
0,123,v|have&past,v,have,past,had
1,121,v|get&past,v,get,past,got
5,32,v|think&past,v,think,past,thought
6,26,v|give&past,v,give,past,gave
7,26,v|take&past,v,take,past,took
11,17,v|buy&past,v,buy,past,bought
12,17,v|come&past,v,come,past,came
14,12,v|know&past,v,know,past,knew
15,12,v|make&past,v,make,past,made
16,11,v|forget&past,v,forget,past,forgot
21,6,v|fall&past,v,fall,past,fell
24,6,v|win&past,v,win,past,won
26,5,v|break&past,v,break,past,broke
32,4,v|sit&past,v,sit,past,sat
35,3,v|mean&past,v,mean,past,meant
42,3,v|write&past,v,write,past,wrote
43,2,v|bite&past,v,bite,past,bit
46,2,v|drink&past,v,drink,past,drank
56,2,v|meet&past,v,meet,past,met
64,2,v|stick&past,v,stick,past,stuck
65,2,v|teach&past,v,teach,past,taught
67,2,v|wake&past,v,wake,past,woke
87,1,v|fly&past,v,fly,past,flew
90,1,v|hide&past,v,hide,past,hid
102,1,v|ride&past,v,ride,past,rode
103,1,v|ring&past,v,ring,past,rang
106,1,v|sing&past,v,sing,past,sang
111,1,v|throw&past,v,throw,past,threw

In [36]:
len(strong_verbs_df)

28

4. Let’s say that this is the verbal lexicon of a young child (a child who only knows this many verbs must be quite young, maybe younger than two). For a child who knows exactly these verbs, is -*ed* productive?

> Yes, *-ed* is productive for a child who knows exactly these verbs because *-ed* is easier to distinguish vs the other types.